# Points to dev database
spring.datasource.url=jdbc:mysql://localhost:3306/gymcrm_dev?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dev Seeding Data
storage.initial-data-file=initial-data/initial-dev-data.json