# Points to staging database
spring.datasource.url=jdbc:mysql://localhost:3306/gymcrm_stg?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# Staging Seeding Data
storage.initial-data-file=initial-data/initial-stg-data.json